package com.example.bestweatherapp.conditions_scheme

data class ConditionsCurrentItem(
    var ApparentTemperature: ApparentTemperature,
    var Ceiling: Ceiling,
    var CloudCover: Int,
    var DewPoint: DewPoint,
    var EpochTime: Int,
    var HasPrecipitation: Boolean,
    var IndoorRelativeHumidity: Int,
    var IsDayTime: Boolean,
    var Link: String,
    var LocalObservationDateTime: String,
    var MobileLink: String,
    var ObstructionsToVisibility: String,
    var Past24HourTemperatureDeparture: Past24HourTemperatureDeparture,
    var Precip1hr: Precip1hr,
    var PrecipitationSummary: PrecipitationSummary,
    var PrecipitationType: String,
    var Pressure: Pressure,
    var PressureTendency: PressureTendency,
    var RealFeelTemperature: RealFeelTemperature,
    var RealFeelTemperatureShade: RealFeelTemperatureShade,
    var RelativeHumidity: Int,
    var Temperature: Temperature,
    var TemperatureSummary: TemperatureSummary,
    var UVIndex: Int,
    var UVIndexText: String,
    var Visibility: Visibility,
    var WeatherIcon: Int,
    var WeatherText: String,
    var WetBulbGlobeTemperature: WetBulbGlobeTemperature,
    var WetBulbTemperature: WetBulbTemperature,
    var Wind: Wind,
    var WindChillTemperature: WindChillTemperature,
    var WindGust: WindGust
)